-- 코드를 입력하세요
SELECT a.APNT_NO, p.PT_NAME, p.PT_NO, d.MCDP_CD, d.DR_NAME, a.APNT_YMD
FROM APPOINTMENT a 
JOIN PATIENT p ON p.PT_NO = a.PT_NO
JOIN DOCTOR d ON d.DR_ID = a.MDDR_ID
WHERE a.APNT_YMD LIKE '2022-04-13%' AND a.APNT_CNCL_YN = 'N'
ORDER BY a.APNT_YMD ASC