SELECT SUM(G.SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E, HR_GRADE G 
WHERE E.EMP_NO = G.EMP_NO AND G.YEAR = 2022
GROUP BY E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
HAVING SUM(G.SCORE) = (
        SELECT MAX(SUM_SCORE)
        FROM (SELECT EMP_NO, SUM(SCORE) AS SUM_SCORE
             FROM HR_GRADE
              WHERE YEAR = 2022
              GROUP BY EMP_NO
             ) AS SUB
        )
        


